### ISSUE TITLE
App no longer works in the latest update

### ISSUE THREAD

**Issue by LiamDawe** [flathub/sh.cider.Cider#305]
Posting here as requested on the official tracker: https://github.com/ciderapp/Cider/issues/1101#issuecomment-1143616010

Describe the Bug

With the latest release available on Linux via Flatpak, the app no longer opens when it worked fine before.
Steps to Reproduce

    Run it on Fedora via Flatpak and see for yourself

Environment Information

    OS: Fedora 36
    App Version and/or Commit ID: v1.5.0-beta.331

Anything else?

Log: https://gist.github.com/LiamDawe/0fcc0466d18e68db40265cae1a5bde04

**Comment by Choff3** [comment]
Seems to be fixed by #304

**Comment by rowbawts** [comment]
> Seems to be fixed by #304

Yup it was a broken build upstream. It's resolved now.
