### ISSUE TITLE
Can't login to last.fm

### ISSUE THREAD

**Issue by Naia-love** [flathub/sh.cider.Cider#357]
please see [here](https://github.com/ciderapp/Cider/issues/1017)

**Comment by rowbawts** [comment]
Ok, I'll look into this first thing in the morning thanks for the report.

**Comment by rowbawts** [comment]
Ok I did some digging and you can read what I've found [here](https://github.com/ciderapp/Cider/issues/1017#issuecomment-1154629101) if you could re-open that issue so they can see it that'd be great. I'm going to leave this issue open in the meantime until we find the solution. Thanks for being patient with this.

**Comment by rowbawts** [comment]
Closed as [upstream](https://github.com/ciderapp/Cider/issues/1017) issue was also closed.
