### ISSUE TITLE
Consider enabling Wayland by default

### ISSUE THREAD

**Issue by Thesola10** [flathub/sh.cider.Cider#474]
After quick testing, the Cider app appears to work just fine with `--enable-features=UseOzonePlatform --ozone-platform=wayland`, and since it provides its own decoration, there's no worry about GNOME Shell not supporting `xdg-decoration`.

**Comment by rowbawts** [comment]
Do you know if setting this on a pure X system will automatically ignore this setting? Because I believe I tried it before and it crashes. That's my main worry I don't want to set a default that will break the app for arguably most people.

**Comment by rowbawts** [comment]
This has been added in PR #480, closed.
