### ISSUE TITLE
The Flatpak is severly out of date, and currently broken.

### ISSUE THREAD

**Issue by Schmensch** [flathub/sh.cider.Cider#495]
Updating to 1.6.1 fixes the issue and is confirmed working on my system (Arch Linux, Cider 1.6.1 from the cider-bin AUR package)

**Comment by rowbawts** [comment]
I updated the beta branch to 1.6.1 yesterday and I'm now deploying the build to the master sorry about the issue.

**Comment by Schmensch** [comment]
Thank you!

**Comment by rowbawts** [comment]
No problem, it should be live any moment. But let's keep the issue open until we verify the update resolves the issue.

**Comment by rowbawts** [comment]
Closing due to stale issue
